name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install deps
        run: npm install

      - name: typecheck
        run: npm run typecheck

      - name: lint
        run: npm run lint