name: Unit Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install deps
        run: npm i

      - name: run unit tests
        run: npm run test
